import { Inter } from 'next/font/google';
import '@/globals.css';
import Header from '@/components/Header';
import CursorFollower from '@/components/CursorFollower';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Smavy Coop',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${inter.className}`}>
				<CursorFollower />
				<Header />
				<main className='max-w-5xl mx-auto pt-20 p-4 z-20'>{children}</main>
			</body>
		</html>
	);
}
