import '@/globals.css';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';

export const metadata = {
	title: 'Smavy Coop',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<Header />
				<main className='mx-auto z-20'>{children}</main>
			</body>
		</html>
	);
}
